In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])  # rank 1 array
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])

a[2] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[1 2 5]


In [3]:
b = np.array([
                [1,2,3],
                [4,5,6],
                [7,8,9]
            ])  # creating a rank 2 array
print(type(b))
print(b.shape)
print(b[0][1])
print(b[2][1])

<class 'numpy.ndarray'>
(3, 3)
2
8


In [4]:
arr_zero = np.zeros( (3,3) )
print(arr_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
arr_ones = np.ones( (3,3) )
print(arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
arr_constant = np.full( (3,3), 4 )
print(arr_constant)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [7]:
arr_identity = np.eye(5)
print(arr_identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
arr_rand = np.random.random((5,5))
print(arr_rand)

[[0.53092845 0.74824736 0.18622072 0.8014033  0.95437372]
 [0.98098785 0.04189312 0.41904589 0.34516849 0.05032533]
 [0.67700499 0.56525155 0.17348714 0.07330502 0.27359116]
 [0.59954354 0.31246623 0.29889358 0.20815    0.12262875]
 [0.78205366 0.88131918 0.09654229 0.42081994 0.44258524]]


In [9]:
# Array Indexing

a = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
            ])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [10]:
b = a[1:3, 2:4]
print(b)
print(b[0][1])


[[ 8  9]
 [13 14]]
9


In [11]:
b[0][0] = 99

print(a)


[[ 1  2  3  4  5]
 [ 6  7 99  9 10]
 [11 12 13 14 15]]


In [12]:
a = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
            ])
row1 = a[1,:] # creating a rank 1 array
row2 = a[1:2, :] # creating rank 2 array
print(row1, row1.shape)
print(row2, row2.shape)

col1 = a[:,1]
col2 = a[:, 1:2]
print(col1, col1.shape)
print(col2, col2.shape)

[ 6  7  8  9 10] (5,)
[[ 6  7  8  9 10]] (1, 5)
[ 2  7 12] (3,)
[[ 2]
 [ 7]
 [12]] (3, 1)


In [13]:
a = np.array([ 
              [1,2],
              [3,4],
              [5,6]
            ])
print(a)

# creating a sub array
print(a[[0,1,2],[0,1,0]]) # shape (3,)
print(np.array([a[0][0], a[1,1], a[2][0]]))   # this is equvalent to the previous statement


print(a[[0,0], [1,1]])
print(np.array([a[0,1], a[0,1]]))   # again this is same as the last statement



[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [14]:
a = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]
            ])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
b = np.array([0,2,0,1])
print(b)

[0 2 0 1]


In [16]:
print(np.arange(4))
print(a[np.arange(4), b])

[0 1 2 3]
[ 1  6  7 11]


In [17]:
a[np.arange(4), b] += 5
print(a)

[[ 6  2  3]
 [ 4  5 11]
 [12  8  9]
 [10 16 12]]


In [18]:
# Boolean array indexing

arr = np.array([
                [1,2,3],
                [4,5,6],
                [7,2,1]
            ])
bool_indx = arr > 2
print(bool_indx)
print(arr[bool_indx])

print(arr[arr>2])

[[False False  True]
 [ True  True  True]
 [ True False False]]
[3 4 5 6 7]
[3 4 5 6 7]


In [19]:
# data types in numpy

a = np.array([1,2,3])
print(a.dtype)

b = np.array([1,2,3.3])
print(b.dtype)

c = np.array([1.1,2.2,3.3], dtype=np.int64)
print(c.dtype)

int64
float64
int64


In [20]:
x = np.array([
                [1,2,3],
                [4,5,6]
            ], dtype=np.float64)
y = np.array([
                [7,8,9],
                [1,2,3]  
            ], dtype=np.float64)

print(x+y)          # Element wise sum
print(np.add(x,y))

print(x-y)          # Element wise subtraction
print(np.subtract(x,y))

print(x*y)          # element wise product
print(np.multiply(x,y))

print(x/y)          # element wise division
print(np.divide(x,y))

print(np.sqrt(x))   # element wise square root

[[ 8. 10. 12.]
 [ 5.  7.  9.]]
[[ 8. 10. 12.]
 [ 5.  7.  9.]]
[[-6. -6. -6.]
 [ 3.  3.  3.]]
[[-6. -6. -6.]
 [ 3.  3.  3.]]
[[ 7. 16. 27.]
 [ 4. 10. 18.]]
[[ 7. 16. 27.]
 [ 4. 10. 18.]]
[[0.14285714 0.25       0.33333333]
 [4.         2.5        2.        ]]
[[0.14285714 0.25       0.33333333]
 [4.         2.5        2.        ]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [21]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

a = np.array([2,3])
b = np.array([4,5])

print(a.dot(b))     # inner product of vectors
print(np.dot(a,b))

print(x.dot(a))     # Matrix / vector product, will produce rank 1 array
print(np.dot(x,a))

print(x.dot(y))     # matrix / matrix product, will produce rank 2 array
print(np.dot(x,y))

23
23
[ 8 18]
[ 8 18]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [22]:
x = np.array([
              [1,2],
              [3,4]
            ])

print(np.sum(x, axis=None))            # sum of all the elements
print(np.sum(x, axis=0))    # sum of each column
print(np.sum(x, axis=1))    # sum of each row

10
[4 6]
[3 7]


In [23]:
print(x.T)      # transpose the matrix
a = np.array([1,2,3,4])
print(a.T)

[[1 3]
 [2 4]]
[1 2 3 4]


In [24]:
# Broadcasting

a = np.array([
                [1,2,3],
                [4,5,6],
                [7,8,9],
                [10,11,12]
            ])
b = np.array([1,2,3])
c = np.empty_like(a) # will create an empty matrix with the same shape as a
print(c)

[[       80618912               0             833]
 [       57904816 139683433103584 139683433103584]
 [139683433103584 139683433103584               0]
 [              4     38654705665               0]]


In [25]:
for i in range(4):
    c[i,:] = a[i, :] + b
print(c)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [28]:
ab = np.tile(b,(4,1))   # stack 4 copies of b on top of each other
print(ab, type(ab))

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>


In [30]:
test = a + ab
print(test)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [32]:
print(a)
print(b)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 2 3]


In [33]:
print(a+b)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [42]:
a = np.array([1,2,3])   # shape(3,)
b = np.array([1,2])     # shape(2,)

# 1st a becomes a colum vector of shape (3,1)
# after the multiplication of b (broadcasting), the shape will be (3,2) 

print(np.reshape(a, (3,1)) * b )


x = np.array([[1,2,3],[4,5,6]])
print(a.shape, x.shape)
print(x+a)

print(x.T + b)
print((x.T + b).T)

print(x + np.reshape(b,(2,1)))

[[1 2]
 [2 4]
 [3 6]]
(3,) (2, 3)
[[2 4 6]
 [5 7 9]]
[[2 6]
 [3 7]
 [4 8]]
[[2 3 4]
 [6 7 8]]
[[2 3 4]
 [6 7 8]]
