In [2]:
import numpy as np

In [6]:
a = np.array([1,2,3])  # rank 1 array
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])

a[2] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[1 2 5]


In [13]:
b = np.array([
                [1,2,3],
                [4,5,6],
                [7,8,9]
            ])  # creating a rank 2 array
print(type(b))
print(b.shape)
print(b[0][1])
print(b[2][1])

<class 'numpy.ndarray'>
(3, 3)
2
8


In [14]:
arr_zero = np.zeros( (3,3) )
print(arr_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
arr_ones = np.ones( (3,3) )
print(arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
arr_constant = np.full( (3,3), 4 )
print(arr_constant)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [17]:
arr_identity = np.eye(5)
print(arr_identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
arr_rand = np.random.random((5,5))
print(arr_rand)

[[0.57142232 0.11888621 0.16789089 0.46534971 0.39035603]
 [0.20306672 0.0273929  0.61657362 0.09649372 0.48697517]
 [0.25587326 0.89868228 0.23775086 0.85930161 0.10685295]
 [0.04683767 0.56823908 0.64857312 0.83438728 0.69150069]
 [0.16403216 0.22020593 0.635187   0.93445785 0.10979501]]


In [19]:
# Array Indexing

a = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
            ])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [21]:
b = a[1:3, 2:4]
print(b)
print(b[0][1])


[[ 8  9]
 [13 14]]
9


In [22]:
b[0][0] = 99

print(a)


[[ 1  2  3  4  5]
 [ 6  7 99  9 10]
 [11 12 13 14 15]]


In [33]:
a = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
            ])
row1 = a[1,:] # creating a rank 1 array
row2 = a[1:2, :] # creating rank 2 array
print(row1, row1.shape)
print(row2, row2.shape)

col1 = a[:,1]
col2 = a[:, 1:2]
print(col1, col1.shape)
print(col2, col2.shape)

[ 6  7  8  9 10] (5,)
[[ 6  7  8  9 10]] (1, 5)
[ 2  7 12] (3,)
[[ 2]
 [ 7]
 [12]] (3, 1)


In [40]:
a = np.array([ 
              [1,2],
              [3,4],
              [5,6]
            ])
print(a)

# creating a sub array
print(a[[0,1,2],[0,1,0]]) # shape (3,)
print(np.array([a[0][0], a[1,1], a[2][0]]))   # this is equvalent to the previous statement


print(a[[0,0], [1,1]])
print(np.array([a[0,1], a[0,1]]))   # again this is same as the last statement



[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [41]:
a = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]
            ])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [42]:
b = np.array([0,2,0,1])
print(b)

[0 2 0 1]


In [44]:
print(np.arange(4))
print(a[np.arange(4), b])

[0 1 2 3]
[ 1  6  7 11]


In [45]:
a[np.arange(4), b] += 5
print(a)

[[ 6  2  3]
 [ 4  5 11]
 [12  8  9]
 [10 16 12]]
